### ISSUE TITLE
trigger automations from dual switch devices with state_l1 and state_l2 attributes

### ISSUE THREAD

**Issue by jirmjos** [Anonym-tsk/zigbee2mqtt-extensions#10]
I'm so sorry for the impertinence but please can you post a quick example how to use a custom action but to trigger automations from a state_l1 or state_l2 ?
I dont understand how to compose this on the trigger: bloc as action like you sugested, not as a custom action to call a service but on the destination device as per defined on the docs.

This is the automation that I compose that I'm not be able to run (is not triggered):

`# automations.yaml

automation_led_comedor_blanca:
  trigger:
    platform: state
    entity: Luz Led comedor
    state_l2:
      - ON
      - OFF
  action:
    - entity: Luz Led blanca comedor
      service: turn_on
    - entity: Luz Led blanca comedor
      service: turn_off`

I've made some crude changes to your code to add state_l1 and state_l2 as triggers. If you want you can check it and perhaps you will understand better what I mean https://github.com/Anonym-tsk/zigbee2mqtt-extensions/issues/9#issuecomment-1548560090

Thank you for your reply

_Originally posted by @jirmjos in https://github.com/Anonym-tsk/zigbee2mqtt-extensions/issues/9#issuecomment-1548574356_

**Comment by Anonym-tsk** [comment]
https://github.com/Anonym-tsk/zigbee2mqtt-extensions/pull/11#issuecomment-1555757837
