### ISSUE TITLE
Action on devices with multiple endpoints

### ISSUE THREAD

**Issue by Cytrian** [Anonym-tsk/zigbee2mqtt-extensions#2]
I have smart switch module (Moes MS-104BZ) with two endpoints:

The state looks like this:
```
{
    "last_seen": "2022-04-12T20:33:16.074Z",
    "linkquality": 83,
    "power_on_behavior": "previous",
    "state_l1": "ON",
    "state_l2": "ON"
}
```
It seems I cannot toggle these, I suggest there should be an "endpoint" attribute in the action, defaulting to "state".

**Comment by Anonym-tsk** [comment]
Look at new custom action
