### ISSUE TITLE
Unable to make automation if device has 2 switches

### ISSUE THREAD

**Issue by LeoeLeoeL** [Anonym-tsk/zigbee2mqtt-extensions#20]
If I want to make an automation using for instance a device with 2 switches, what should I write as entity?
The friendly name is for device.

**Comment by iantait** [comment]
if you look in 'devices' -> your device -> state, in z2m - I have a switch that exposes 2 devices - it looks like this:
`{
    "backlight_mode": "medium",
    "child_lock": "UNLOCK",
    "linkquality": 91,
    "power_on_behavior": "off",
    "power_on_behavior_l1": "previous",
    "state_l1": "OFF",
    "state_l2": "ON"
}`

In this case, state_l1 and state_l2 are the individual switches.
You could then reference one of the switches like this:

`automation_by_action_49:
  trigger:
    platform: state
    entity: back door sensor
    attribute: occupancy
    state: false
    for: 20
  action:
    entity: shed external socket
    service: custom
    data:
      state_l1: off`

**Comment by Anonym-tsk** [comment]
Please read the doc
https://github.com/Anonym-tsk/zigbee2mqtt-extensions?tab=readme-ov-file#custom-action

**Comment by LeoeLeoeL** [comment]
OK, I read the doc but it's for action. What about the trigger?

![image](https://github.com/Anonym-tsk/zigbee2mqtt-extensions/assets/65825223/7fb6c6c4-4924-4da0-9c70-3d856f2c27e8)

Where is my error?

**Comment by LeoeLeoeL** [comment]
![image](https://github.com/Anonym-tsk/zigbee2mqtt-extensions/assets/65825223/e3f6f2a4-64fd-4a5a-9c60-b9835587b60f)

Same behaviour, It doesn't work.

**Comment by Anonym-tsk** [comment]
```yaml
trigger:
  platform: state
  entity: Switch
  attribute: state_l2
  state: ON
```

**Comment by LeoeLeoeL** [comment]
Perfect.
Tks.
