### ISSUE TITLE
Предложение вынести автоматизации в automations.yaml

### ISSUE THREAD

**Issue by DaN66O** [Anonym-tsk/zigbee2mqtt-extensions#3]
Если это возможно конечно...
Вынести автоматизации в automations.yaml
В файле configuration.yaml указать что то типа 
automations: automations.yaml
p.s.
Или просто парсить отдельный файл automations.yaml без указания его в основном configuration.yaml

**Comment by Anonym-tsk** [comment]
Fixed in d0fb0c74f06aedd9b862c72f6683b87a50333efe
