### ISSUE TITLE
How to add more than 1 automation_by_action to configuration.yaml

### ISSUE THREAD

**Issue by rikmueller** [Anonym-tsk/zigbee2mqtt-extensions#4]
Great extension! 
I´d like to add more than one automation_by_action to configuration.yaml, but it doesn´t work.
It always ends up with duplicate mapping keys and z2m won´t start.

Either it´s a bug or I´m doing something wrong.

**Comment by Anonym-tsk** [comment]
Please provide your configuration example

**Comment by rikmueller** [comment]
Sorry for the dumb question, figured it out myself.
I used "- automation_name" for every new automation (problem was the "-").
Thanks!
