### ISSUE TITLE
How do I add more than 1 automation_by_action Automation

### ISSUE THREAD

**Issue by baerenmarke90** [Anonym-tsk/zigbee2mqtt-extensions#5]
Hi,

I'd like to use different actions for my Hue tap button switch. The first action isn't a problem, but when I want to configure the other 3 buttons, z2m won't start anymore with: duplicate mapping.

Could you pls help me?

#Gast Taster Hue Tap
automation_by_action:
  trigger:
    platform: action
    entity: Gast Taster Hue Tap
    action: press_1
  action:
    entity: Gast Lampe
    service: toggle
automation_by_action:
  trigger:
    platform: action
    entity: Gast Taster Hue Tap
    action: press_2
  action:
    entity: Gast Stehlampe
    service: toggle
automation_by_action:
  trigger:
    platform: action
    entity: Gast Taster Hue Tap
    action: press_3
  action:
    entity: Gast TV
    service: toggle
automation_by_action:
  trigger:
    platform: action
    entity: Gast Taster Hue Tap
    action: press_4
  action:
    entity: Gast Multimedia
    service: toggle

**Comment by baerenmarke90** [comment]
Okay, I'm stupid 👯 
I have to rename the automations, no it works:

#Gast Taster Hue Tap
automation_by_action_1:
  trigger:
    platform: action
    entity:
    - Gast Taster Hue Tap
    action:
    - press_1
  action:
  - entity: Gast Lampe
    service: toggle
automation_by_action_2:
  trigger:
    platform: action
    entity:
     - Gast Taster Hue Tap
    action:
    - press_2
  action:
  - entity: Gast Stehlampe
  -  service: toggle
automation_by_action_3:
  trigger:
    platform: action
    entity: 
     - Gast Taster Hue Tap
    action:
    - press_3
  action:
  - entity: Gast TV
    service: toggle
automation_by_action_4:
  trigger:
    platform: action
    entity:
     - Gast Taster Hue Tap
    action:
    - press_4
  action:
  - entity: Gast Multimedia
    service: toggle

**Comment by Anonym-tsk** [comment]
So, does it work now?

**Comment by baerenmarke90** [comment]
yes, thank you!
