### ISSUE TITLE
What is the correct way to install automations-extension.js ?

### ISSUE THREAD

**Issue by jirmjos** [Anonym-tsk/zigbee2mqtt-extensions#8]
Hi,
I`m newby on z2m and I need test your automations extension but seeing all the whole files on github repository and see instructions on (https://www.zigbee2mqtt.io/advanced/more/user_extensions.html) still cannot figure what files from your github and how to propper install them on z2m.

Thanks.

**Comment by Anonym-tsk** [comment]
Open Extensions page in z2m frontend, create new extension and copy content from `dist/automations-extension.js` file there.
Then create your first automation in `configuration.yaml` file.

**Comment by maltejahn** [comment]
Hi,

this seems to be too easy that im hesitating to ask:
Z2M -> Extensions: Green plus sign, give it a name automate-extension.js. Remove the example code and replace it with your code(raw). 
Finally click "Save"

With this, i get an error message:
Request 'zigbee2mqtt/bridge/request/extension/save' failed with error: 'Cannot use import statement outside a module'

If i just add the extension into /opt/zigbee2mqtt/data/extension (like described here: https://www.zigbee2mqtt.io/advanced/more/user_extensions.html) and do a restart of the zigbee2mqtt service -> it doenst appear (as a mqtt message). With the described example (MyExampleExtension ) it seems to work.

**Comment by maltejahn** [comment]
So I answer this myself. It was a permission error: (like EACCES no permission,...)

<code>
chown -R pi /opt/zigbee2mqtt
chgrp -R pi /opt/zigbee2mqtt
</code>
https://github.com/Koenkk/zigbee2mqtt/issues/10591

**Comment by earcam** [comment]
Just to note;  for non-UI / scripted install - you may just copy the **.js** script into z2m's configuration directory (and then bounce instance to pick up change)

With v2 it's **./external-extension** (IIRC older z2m versions the directory is **./extension**)


(@Anonym-tsk kudos and thank you for sharing & maintaining this;  you've literally been _keeping the lights_ on in my home)
