### ISSUE TITLE
Cannot trigger with state_l1 and state_l2 for dual switch devices

### ISSUE THREAD

**Issue by jirmjos** [Anonym-tsk/zigbee2mqtt-extensions#9]
I have uploaded this awesome automation plugin for Z2M which works great but I have verified that it lacks a feature to trigger from dual switch devices which do not have a single default state and instead dual devices have two states for each swtich which are state_l1 and state_l2 corresponding to the left and the right switch.

So I ask to add this function because I think it will be very useful for anyone and in my case it is necessary to be able to activate several automations through double switches.

Thank you so much.
Jose

**Comment by jirmjos** [comment]
I've made a crude modification of your code to add the possibility of firing from dual switch with state_l1 and state_l2 for what it's worth.
I have not yet been able to verify if this could work but in any case I consider it more appropriate that the owner of the code is the one who reviews it and, if necessary, makes the most appropriate modifications according to his criteria.

`const stringify = require("json-stable-stringify-without-jsonify");
const crypto = require("crypto");
const yaml_1 = require("../util/yaml");
const data_1 = require("../util/data");
function toArray(item) {
    return Array.isArray(item) ? item : [item];
}
var ConfigPlatform;
(function (ConfigPlatform) {
    ConfigPlatform["ACTION"] = "action";
    ConfigPlatform["STATE"] = "state";
    ConfigPlatform["STATE_L1"] = "state_l1";
    ConfigPlatform["STATE_L2"] = "state_l2";
    ConfigPlatform["NUMERIC_STATE"] = "numeric_state";
})(ConfigPlatform || (ConfigPlatform = {}));
var StateOnOff;
(function (StateOnOff) {
    StateOnOff["ON"] = "ON";
    StateOnOff["OFF"] = "OFF";
})(StateOnOff || (StateOnOff = {}));
var ConfigService;
(function (ConfigService) {
    ConfigService["TOGGLE"] = "toggle";
    ConfigService["TURN_ON"] = "turn_on";
    ConfigService["TURN_OFF"] = "turn_off";
    ConfigService["CUSTOM"] = "custom";
})(ConfigService || (ConfigService = {}));
class InternalLogger {
    constructor(logger) {
        this.logger = logger;
    }
    log(level, ...args) {
        const data = args.map((item) => typeof item === 'string' ? item : stringify(item)).join(' ');
        this.logger[level](`[AutomationsExtension] ${data}`);
    }
    debug(...args) {
        this.log('debug', ...args);
    }
    warning(...args) {
        this.log('warning', ...args);
    }
    info(...args) {
        this.log('info', ...args);
    }
    error(...args) {
        this.log('error', ...args);
    }
}
class AutomationsExtension {
    constructor(zigbee, mqtt, state, publishEntityState, eventBus, settings, baseLogger) {
        this.zigbee = zigbee;
        this.mqtt = mqtt;
        this.state = state;
        this.publishEntityState = publishEntityState;
        this.eventBus = eventBus;
        this.settings = settings;
        this.logger = new InternalLogger(baseLogger);
        this.mqttBaseTopic = settings.get().mqtt.base_topic;
        this.automations = this.parseConfig(settings.get().automations || {});
        this.timeouts = {};
        this.logger.info('Plugin loaded');
        this.logger.debug('Registered automations', this.automations);
    }
    parseConfig(automations) {
        if (typeof automations === 'string') {
            automations = (yaml_1.default.readIfExists(data_1.default.joinPath(automations)) || {});
        }
        const services = Object.values(ConfigService);
        const platforms = Object.values(ConfigPlatform);
        return Object.values(automations).reduce((result, automation) => {
            const platform = automation.trigger.platform;
            if (!platforms.includes(platform)) {
                this.logger.warning(`Config validation error: unknown trigger platform '${platform}'`);
                return result;
            }
            if (!automation.trigger.entity) {
                this.logger.warning('Config validation error: trigger entity not specified');
                return result;
            }
            const actions = toArray(automation.action);
            for (const action of actions) {
                if (!services.includes(action.service)) {
                    this.logger.warning(`Config validation error: unknown service '${action.service}'`);
                    return result;
                }
            }
            const conditions = automation.condition ? toArray(automation.condition) : [];
            for (const condition of conditions) {
                if (!condition.entity) {
                    this.logger.warning('Config validation error: condition entity not specified');
                    return result;
                }
                if (!platforms.includes(condition.platform)) {
                    this.logger.warning(`Config validation error: unknown condition platform '${condition.platform}'`);
                    return result;
                }
            }
            const entities = toArray(automation.trigger.entity);
            for (const entityId of entities) {
                if (!result[entityId]) {
                    result[entityId] = [];
                }
                result[entityId].push({
                    id: crypto.randomUUID(),
                    trigger: automation.trigger,
                    action: actions,
                    condition: conditions,
                });
            }
            return result;
        }, {});
    }
    checkTrigger(configTrigger, update, from, to) {
        let trigger;
        let attribute;
        switch (configTrigger.platform) {
            case ConfigPlatform.ACTION:
                if (!update.hasOwnProperty('action')) {
                    return null;
                }
                trigger = configTrigger;
                const actions = toArray(trigger.action);
                return actions.includes(update.action);
            case ConfigPlatform.STATE:
                trigger = configTrigger;
                attribute = trigger.attribute || 'state';
                if (!update.hasOwnProperty(attribute) || !from.hasOwnProperty(attribute) || !to.hasOwnProperty(attribute)) {
                    return null;
                }
                if (from[attribute] === to[attribute]) {
                    return null;
                }
                const states = toArray(trigger.state);
                return states.includes(update[attribute]);
            case ConfigPlatform.STATE_L1:
                trigger = configTrigger;
                attribute = trigger.attribute || 'state_l1';
                if (!update.hasOwnProperty(attribute) || !from.hasOwnProperty(attribute) || !to.hasOwnProperty(attribute)) {
                    return null;
                }
                if (from[attribute] === to[attribute]) {
                    return null;
                }
                const states = toArray(trigger.state);
                return states.includes(update[attribute]);
            case ConfigPlatform.STATE_L2:
                trigger = configTrigger;
                attribute = trigger.attribute || 'state_l2';
                if (!update.hasOwnProperty(attribute) || !from.hasOwnProperty(attribute) || !to.hasOwnProperty(attribute)) {
                    return null;
                }
                if (from[attribute] === to[attribute]) {
                    return null;
                }
                const states = toArray(trigger.state);
                return states.includes(update[attribute]);
            case ConfigPlatform.NUMERIC_STATE:
                trigger = configTrigger;
                attribute = trigger.attribute;
                if (!update.hasOwnProperty(attribute) || !from.hasOwnProperty(attribute) || !to.hasOwnProperty(attribute)) {
                    return null;
                }
                if (from[attribute] === to[attribute]) {
                    return null;
                }
                if (typeof trigger.above !== 'undefined') {
                    if (to[attribute] < trigger.above) {
                        return false;
                    }
                    if (from[attribute] >= trigger.above) {
                        return null;
                    }
                }
                if (typeof trigger.below !== 'undefined') {
                    if (to[attribute] > trigger.below) {
                        return false;
                    }
                    if (from[attribute] <= trigger.below) {
                        return null;
                    }
                }
                return true;
        }
        return false;
    }
    checkCondition(condition) {
        const entity = this.zigbee.resolveEntity(condition.entity);
        if (!entity) {
            this.logger.debug(`Condition not found for entity '${condition.entity}'`);
            return true;
        }
        let currentCondition;
        let currentState;
        let attribute;
        switch (condition.platform) {
            case ConfigPlatform.STATE:
                currentCondition = condition;
                attribute = currentCondition.attribute || 'state';
                currentState = this.state.get(entity)[attribute];
                if (currentState !== currentCondition.state) {
                    return false;
                }
                break;
            case ConfigPlatform.NUMERIC_STATE:
                currentCondition = condition;
                attribute = currentCondition.attribute;
                currentState = this.state.get(entity)[attribute];
                if (typeof currentCondition.above !== 'undefined' && currentState < currentCondition.above) {
                    return false;
                }
                if (typeof currentCondition.below !== 'undefined' && currentState > currentCondition.below) {
                    return false;
                }
                break;
        }
        return true;
    }
    runActions(actions) {
        for (const action of actions) {
            const destination = this.zigbee.resolveEntity(action.entity);
            if (!destination) {
                this.logger.debug(`Destination not found for entity '${action.entity}'`);
                continue;
            }
            const currentState = this.state.get(destination).state;
            let newState;
            switch (action.service) {
                case ConfigService.TURN_ON:
                    newState = StateOnOff.ON;
                    break;
                case ConfigService.TURN_OFF:
                    newState = StateOnOff.OFF;
                    break;
                case ConfigService.TOGGLE:
                    newState = currentState === StateOnOff.ON ? StateOnOff.OFF : StateOnOff.ON;
                    break;
            }
            let data;
            if (action.service === ConfigService.CUSTOM) {
                data = action.data;
            }
            else if (currentState === newState) {
                continue;
            }
            else {
                data = { state: newState };
            }
            this.logger.debug(`Run automation for entity '${action.entity}':`, action);
            this.mqtt.onMessage(`${this.mqttBaseTopic}/${destination.name}/set`, stringify(data));
        }
    }
    runActionsWithConditions(conditions, actions) {
        for (const condition of conditions) {
            if (!this.checkCondition(condition)) {
                return;
            }
        }
        this.runActions(actions);
    }
    stopTimeout(automationId) {
        const timeout = this.timeouts[automationId];
        if (timeout) {
            clearTimeout(timeout);
            delete this.timeouts[automationId];
        }
    }
    startTimeout(automation, time) {
        this.logger.debug('Start timeout for automation', automation.trigger);
        const timeout = setTimeout(() => {
            delete this.timeouts[automation.id];
            this.runActionsWithConditions(automation.condition, automation.action);
        }, time * 1000);
        timeout.unref();
        this.timeouts[automation.id] = timeout;
    }
    runAutomationIfMatches(automation, update, from, to) {
        const triggerResult = this.checkTrigger(automation.trigger, update, from, to);
        if (triggerResult === false) {
            this.stopTimeout(automation.id);
            return;
        }
        if (triggerResult === null) {
            return;
        }
        this.logger.debug('Start automation', automation);
        const timeout = this.timeouts[automation.id];
        if (timeout) {
            return;
        }
        if (automation.trigger.for) {
            this.startTimeout(automation, automation.trigger.for);
            return;
        }
        this.runActionsWithConditions(automation.condition, automation.action);
    }
    findAndRun(entityId, update, from, to) {
        const automations = this.automations[entityId];
        if (!automations) {
            return;
        }
        for (const automation of automations) {
            this.runAutomationIfMatches(automation, update, from, to);
        }
    }
    async start() {
        this.eventBus.onStateChange(this, (data) => {
            this.findAndRun(data.entity.name, data.update, data.from, data.to);
        });
    }
    async stop() {
        this.eventBus.removeListeners(this);
    }
}
module.exports = AutomationsExtension;`
[automations-extension.zip](https://github.com/Anonym-tsk/zigbee2mqtt-extensions/files/11481913/automations-extension.zip)

**Comment by Anonym-tsk** [comment]
Use [custom action](https://github.com/Anonym-tsk/zigbee2mqtt-extensions#custom-action) for dual switch devices.

**Comment by jirmjos** [comment]
> Use [custom action](https://github.com/Anonym-tsk/zigbee2mqtt-extensions#custom-action) for dual switch devices

Please can you post a quick example how to use custom action to trigger automation from a state_l1 or state_l2 ?
I dont understand how to compose this action on the trigger block and not like a custom action but for the destination device
Thank you for your reply

**Comment by Anonym-tsk** [comment]
https://github.com/Anonym-tsk/zigbee2mqtt-extensions/pull/11#issuecomment-1555757837
